import{a as L,i as l,S as w}from"./assets/vendor-DHjmJuTs.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(o){if(o.ep)return;o.ep=!0;const r=i(o);fetch(o.href,r)}})();const S=15,E="53062520-ab6df8030023bb65348d73bcb",q="https://pixabay.com/api/",P=L.create({baseURL:q,params:{key:E,image_type:"photo",orientation:"horizontal",safesearch:!0}});async function v(t,e=1,i=S){const{data:n}=await P.get("",{params:{q:t,page:e,per_page:i}});return n}function M(t){return t.map(({webformatURL:e,largeImageURL:i,tags:n,likes:o,views:r,comments:s,downloads:b})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${e}" alt="${A(n)}" loading="lazy" />
        </a>
        <ul class="meta">
          <li><b>Likes:</b> ${o}</li>
          <li><b>Views:</b> ${r}</li>
          <li><b>Comments:</b> ${s}</li>
          <li><b>Downloads:</b> ${b}</li>
        </ul>
      </li>`).join("")}function R(t){document.querySelector("#gallery").insertAdjacentHTML("beforeend",t)}function $(){document.querySelector("#gallery").innerHTML=""}function u(t){const e=document.querySelector("#load-more");e.hidden=!t,e.disabled=!1}function g(t){const e=document.querySelector("#loader");e.hidden=!t}function A(t=""){return t.replace(/[&<>"']/g,e=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[e])}const B=document.getElementById("search-form"),d=document.getElementById("load-more");let f="",a=1;const p=15;let y=0,c=null,m=!1;B.addEventListener("submit",I);d.addEventListener("click",O);async function I(t){if(t.preventDefault(),f=t.currentTarget.elements.query.value.trim(),!f){l.warning({title:"Увага",message:"Введіть пошуковий запит!",position:"topRight"});return}a=1,$(),u(!1),await h()}async function O(){m||(a+=1,await h(!0))}async function h(t=!1){m=!0,g(!0),d.disabled=!0;try{const e=await v(f,a,p),i=e?.hits??[];if(i.length===0&&a===1){l.info({title:"Упс!",message:"За цим запитом нічого не знайдено. Спробуйте інше ключове слово.",position:"topRight"}),u(!1);return}const n=M(i);R(n),c?c.refresh():c=new w(".gallery a",{captionsData:"alt",captionDelay:250}),y=e?.totalHits??0;const o=Math.ceil(y/p);u(a<o),a>=o&&a!==1&&l.info({title:"Кінець колекції",message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"}),t&&_()}catch(e){l.error({title:"Помилка",message:e?.message||"Something went wrong",position:"topRight"})}finally{g(!1),d.disabled=!1,m=!1}}function _(){const t=document.querySelector(".gallery-item");if(!t)return;const{height:e}=t.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
